id: I784E178B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:58:41+00:00'
last_modified: '2022-06-16T04:06:37.225020+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3655
  title: འཇའ་ཚོན་པོད་དྲུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8710':
      image_group_id: I1KG4164
      title: Volume 1 of gter chos/_'ja' tshon snying po
      total_pages: 608
      order: 1
      base_file: 8710.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
