id: I784E178B
legacy_id: P000487
ocr_import_info:
  bdrc_scan_id: W1KG3655
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T09:53:02'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:11:38.864874+00:00'
last_modified: 2022-08-31 23:12:48.548834
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3655
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3655
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇའ་ཚོན་པོད་དྲུག
  author: འཇའ་ཚོན་སྙིང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8020856252331391
  ocr_word_median_confidence_index: 0.8899999856948853
quality: null
bases:
  I1KG4164:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4164
      total_pages: 608
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4164.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.791369275984799
    legacy_id: v001
  I1KG4167:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4167
      total_pages: 488
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG4167.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8018166442127462
    legacy_id: v004
  I1KG4165:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4165
      total_pages: 674
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG4165.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.829192371465677
    legacy_id: v002
  I1KG4168:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4168
      total_pages: 712
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG4168.txt
    statistics:
      ocr_word_median_confidence_index: 0.9100000262260437
      ocr_word_mean_confidence_index: 0.805819380155206
    legacy_id: v005
  I1KG4169:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4169
      total_pages: 842
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG4169.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7946638462417543
    legacy_id: v006
  I1KG4166:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4166
      total_pages: 396
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG4166.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.7914594698630811
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
